# Generated by Django 5.2.6 on 2025-09-29 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
