# Generated by Django 5.2.6 on 2025-10-06 20:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('mysql', 'MySQL'), ('postgres', 'PostgreSQL'), ('oracle', 'Oracle'), ('mssql', 'MSSQL'), ('redshift', 'Redshift'), ('bigquery', 'BigQuery'), ('snowflake', 'Snowflake'), ('teradata', 'Teradata')], max_length=50)),
                ('connection_mode', models.CharField(choices=[('local', 'Local'), ('cloud', 'Cloud')], max_length=10)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('database', models.CharField(blank=True, max_length=255, null=True)),
                ('local_url', models.CharField(blank=True, max_length=255, null=True)),
                ('local_token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
