# Generated by Django 5.2.6 on 2025-10-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_externalconnection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalConnection',
        ),
    ]
