# Generated by Django 5.2.6 on 2025-10-20 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_externalconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.CharField(blank=True, max_length=16, null=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('_password', models.TextField(blank=True, db_column='password', null=True)),
                ('database', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'connector_id', 'host', 'port', 'username', 'database')},
            },
        ),
    ]
