# Generated by Django 5.2.6 on 2025-10-20 18:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_datasourceconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasourceconnection',
            name='id',
        ),
        migrations.AlterField(
            model_name='datasourceconnection',
            name='connector_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
